// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Index2: typeof import('./../../src/components/toast-msg/index2.vue')['default']
    Loading: typeof import('./../../src/components/loading/loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastMsg: typeof import('./../../src/components/toast-msg/index.vue')['default']
  }
}
