/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Index2: typeof import('./../../src/components/ToastMsg/index2.vue')['default']
    Loading: typeof import('./../../src/components/Loading/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastMsg: typeof import('./../../src/components/ToastMsg/index.vue')['default']
  }
}
