// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../../src/components/HelloWorld/HelloWorld.vue')['default']
    Inject: typeof import('./../../src/components/Inject/Inject.vue')['default']
    Loading: typeof import('./../../src/components/Loading/Loading.vue')['default']
    Message: typeof import('./../../src/components/Message/Message.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
